Test commit
Signed-off-by: Santosh Kaluskar <ksantosh@intelops.dev>

diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -1,6 +1,6 @@
 repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
-  rev: v4.5.0 
+  rev: v4.5.0
   hooks:
   # Checks for files that contain merge conflict strings.
   - id: check-merge-conflict
@@ -9,13 +9,19 @@ repos:
     args: [--allow-missing-credentials]
   # detects the presence of private keys.
   - id: detect-private-key
-  # Verifies that test files are named correctly.
-  - id: name-tests-test
   # Trims trailing whitespace in codebase.
   - id: trailing-whitespace
   # Protect commit to main branch
   - id: no-commit-to-branch
     args: [--branch,main]
+
+
+# Check is the Commit is Signed off using `--signoff/-s`
+- repo: https://github.com/KAUTH/pre-commit-git-checks
+  rev: v0.0.1 # Use the SHA or tag you want to point to
+  hooks:
+    - id: git-signoff
+      stages: [commit-msg]
 
 # Checks your git commit messages for style.
 - repo: https://github.com/jorisroovers/gitlint
@@ -25,25 +31,107 @@ repos:
     name: Scan Commit messages
 
 # Detects hardcoded secrets, security vulnerabilities and policy breaks using GGShield
-- repo: https://github.com/gitguardian/gg-shield
-  rev: v1.22.0
+- repo: https://github.com/zricethezav/gitleaks
+  rev: v8.18.1
   hooks:
-  - id: ggshield
-    name: Scan Secrets
+  - id: gitleaks
+    name: Detect hardcoded secrets
+    description: Detect hardcoded secrets using Gitleaks
+    entry: gitleaks protect --verbose --redact --staged
+    language: golang
+    pass_filenames: false
 
-# Golang specific Hooks
-# Enforce a stricter Go format than gofmt
-- repo: https://github.com/mvdan/gofumpt
-  rev: v0.5.0
-  hooks:
-  - id: gofumpt
-    name: Extended Go Format
 
-# Runs unit/integration tests in the repo
-- repo: https://github.com/TekWizely/pre-commit-golang
-  rev: v1.0.0-rc.1
+
+- repo: https://github.com/Bahjat/pre-commit-golang
+  rev: v1.0.3
   hooks:
-  - id: go-test-mod
-    name: Run Tests
-  - id: go-test-pkg
-  # args: [] 
+  # Formats Go code
+  # - id: gofumpt # requires gofumpt to be installed from github.com/mvdan/gofumpt
+  #   name: Go formatter
+  #   description: Runs a strict Go formatter
+  - id: go-fmt-import
+    name: Go formatter
+    description: Go formatter with fmt and imports
+  # Runs Unit tests
+  # - id: go-unit-tests
+  #   name: Run Unit tests
+  #   desription: Runs all the unit tests in the repo
+    # Runs static analysis of the Go code
+  - id: go-static-check
+    name: Go Static Check
+    description: Finds bugs and performance issues
+
+# Local hooks
+# Check for devcontainer.json in the project
+# - repo: local
+#   hooks:
+#   - name: Check devcontainer
+#     id: check-devcontainer-sh
+#     entry: bash
+#     args:
+#     - -c
+#     - |
+#         DEVCONTAINER_PATH="./devcontainer.json"
+#         YELLOW='\033[1;33m'
+#         NC='\033[0m' # No Color
+#         if [ ! -f "$DEVCONTAINER_PATH" ]; then
+#             echo -e "${YELLOW}WARNING: devcontainer.json is missing.${NC}"
+#             echo "It's recommended to add a devcontainer.json file."
+#         else
+#             echo "devcontainer.json found."
+#         fi
+#         exit 1
+#     language: system
+#     pass_filenames: false
+
+# Check for Dockerfile in a project
+- repo: local
+  hooks:
+  - name: Check Dockerfile
+    id: check-dockerfile-sh
+    entry: bash
+    args:
+    - -c
+    - |
+        check_dockerfile() {
+        if [[ $1 == *"Dockerfile"* ]]; then
+              base_image=$(grep '^FROM' "$1" | awk '{print $2}')
+            if [[ $base_image != cgr.dev/chianguard* ]]; then
+                echo "Error: Base image in $1 is not from cgr.dev/chianguard"
+                return 1
+            fi
+        fi
+        return 0
+        }
+
+        export -f check_dockerfile
+        if find . -type f -exec bash -c 'check_dockerfile "$0"' {} \; | grep -q 'Error'; then
+          echo "Commit failed due to non-compliant Dockerfile(s)."
+          exit 1
+        fi
+
+        echo "All Dockerfiles are compliant."
+        exit 0
+    language: system
+    pass_filenames: false
+
+# Check commit signed by gitsign
+- repo: local
+  hooks:
+  - name: Check GitSign
+    id: check-gitsign-sh
+    entry: bash
+    args:
+    - -c
+    - |
+        latest_commit=$(git rev-parse HEAD)
+        signed_commit=$(git verify-commit $latest_commit 2>&1)
+        if [[ $signed_commit == *"Validated Git signature: true"* ]]; then
+            echo "Latest commit is signed with gitsign."
+        else
+            echo "WARNING: The latest commit is not signed with gitsign."
+        fi
+        exit 1
+    language: system
+    pass_filenames: false
